# hosts/yomi-strix/hardware.nix — REAL hardware profile (first iteration).
#
# Ported from dxflake's yomi-strix (the template), trimmed to essentials.
# dxflake used disko for partitioning; Aoide does not manage disks, so the
# fileSystems generated by that layout are pinned here by UUID, read from the
# LIVE box (single NVMe: 1G vfat ESP + ext4 root). Regenerate with
# `nixos-generate-config --show-hardware-config` if the disk ever changes.
{
  config,
  lib,
  modulesPath,
  ...
}:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # ── Disk (matches the disko-created layout on /dev/nvme0n1) ───────────────
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/b4e40cd3-9113-4d16-9c9b-eda82253d8c8";
    fsType = "ext4";
  };
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/8E8D-D159";
    fsType = "vfat";
    options = [ "umask=0077" ];
  };

  # ── Boot: UEFI + systemd-boot (dxflake nucleus baseline) ──────────────────
  boot.loader = {
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
  };

  # ── Kernel module set (dxflake scan baseline for Strix Halo) ──────────────
  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [
    "nvme"
    "amdgpu" # early KMS on the RDNA 3.5 iGPU
  ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
