//! The kitty colour emitter — a staged song's terminal colours in kitty's
//! own config syntax (`stage/terminal-colors.conf`).
//!
//! The mapping is the tinted-kitty `base16` template's, key for key — the
//! same template Stylix renders into the declared kitty.conf include — so a
//! re-pin to the declared song writes exactly the colours the baked config
//! already carries, and staging a song differs from declaring it only in
//! WHICH song, never in how its base16 lands on the terminal:
//!
//! * basics: background base00, foreground base05, selection base03/base05,
//!   cursor base05 on base00, url base04, kitty's own borders base03/base01,
//!   titlebar base00, tabs base00/base05 active and base01/base04 inactive;
//! * the sixteen ANSI slots: 0 base00, 1 base08, 2 base0B, 3 base0A,
//!   4 base0D, 5 base0E, 6 base0C, 7 base05, 8 base02, 9–14 repeat 1–6,
//!   15 base07; and the extended 16–21: base09 base0F base01 base02 base04
//!   base06.
//!
//! A note with no base16 tier gets the scheme the Stylix facet synthesises
//! for the baked side (`modules/facets/stylix/default.nix`,
//! `synthesisedScheme` — [`synthesised_base16`] is its slot-for-slot twin),
//! so EVERY slot is written either way. The file is complete on its own: a
//! push never has to reset first, and no slot of an earlier song survives a
//! palette-only stage. (`set-colors --reset` could not do that job — kitty
//! resets to the colours it had at startup, which include whatever staged
//! file was on disk then, not the baked baseline.)
//!
//! Every value is hex-linted before it is written: this file is an
//! `include` in every new kitty window's config, so a value carrying a
//! newline would be a second config directive. A non-hex value drops its
//! line — the same "no opinion" treatment `live::geometry_keywords` gives a
//! non-hex border.

use crate::livery::emit::{EmitError, EmitOpts, EmitOutput, Emitter};
use crate::livery::resolve::{with_hash, Resolved};
use crate::livery::schema;

/// The kitty colour-file emitter.
pub struct Kitty;

impl Emitter for Kitty {
    fn target(&self) -> &'static str {
        "kitty"
    }

    fn emit(&self, r: &Resolved, _o: &EmitOpts) -> Result<EmitOutput, EmitError> {
        Ok(EmitOutput::Text(emit_kitty(r)))
    }
}

/// kitty key → base16 slot, in the tinted-kitty template's order.
const BASE16_MAP: &[(&str, &str)] = &[
    ("background", "base00"),
    ("foreground", "base05"),
    ("selection_background", "base03"),
    ("selection_foreground", "base05"),
    ("cursor", "base05"),
    ("cursor_text_color", "base00"),
    ("url_color", "base04"),
    ("active_border_color", "base03"),
    ("inactive_border_color", "base01"),
    ("wayland_titlebar_color", "base00"),
    ("macos_titlebar_color", "base00"),
    ("active_tab_background", "base00"),
    ("active_tab_foreground", "base05"),
    ("inactive_tab_background", "base01"),
    ("inactive_tab_foreground", "base04"),
    ("tab_bar_background", "base01"),
    ("color0", "base00"),
    ("color1", "base08"),
    ("color2", "base0B"),
    ("color3", "base0A"),
    ("color4", "base0D"),
    ("color5", "base0E"),
    ("color6", "base0C"),
    ("color7", "base05"),
    ("color8", "base02"),
    ("color9", "base08"),
    ("color10", "base0B"),
    ("color11", "base0A"),
    ("color12", "base0D"),
    ("color13", "base0E"),
    ("color14", "base0C"),
    ("color15", "base07"),
    ("color16", "base09"),
    ("color17", "base0F"),
    ("color18", "base01"),
    ("color19", "base02"),
    ("color20", "base04"),
    ("color21", "base06"),
];

/// base16 slot → (group, field) for a note with no base16 tier — the Stylix
/// facet's `synthesisedScheme`, slot for slot. `"palette"` reads the anchor
/// itself; the component groups arrive with the resolver's null→palette
/// fallback already applied, exactly as the facet's `resolved` set applies
/// it.
const SYNTHESISED: &[(&str, (&str, &str))] = &[
    ("base00", ("palette", "bg")),
    ("base01", ("bar", "bg")),
    ("base02", ("window", "borderInactive")),
    ("base03", ("palette", "fg")),
    ("base04", ("palette", "fg")),
    ("base05", ("palette", "fg")),
    ("base06", ("palette", "fg")),
    ("base07", ("palette", "fg")),
    ("base08", ("notif", "urgent")),
    ("base09", ("palette", "accent")),
    ("base0A", ("palette", "accent")),
    ("base0B", ("palette", "accent")),
    ("base0C", ("palette", "accent")),
    ("base0D", ("window", "border")),
    ("base0E", ("bar", "accent")),
    ("base0F", ("palette", "urgent")),
];

const HEADER: &str =
    "# Generated by aoide-song (`rice stage`): the staged song's terminal colours.\n\
                      # Rewritten on every stage and declarative re-pin; never edit by hand.\n";

fn get<'a>(tier: &'a [(String, String)], key: &str) -> Option<&'a str> {
    tier.iter().find(|(k, _)| k == key).map(|(_, v)| v.as_str())
}

/// The base16 scheme the baked side derives for a note with no base16 tier
/// (see [`SYNTHESISED`]). The resolver guarantees all four anchors and every
/// component field, so all sixteen slots come back.
pub fn synthesised_base16(r: &Resolved) -> Vec<(String, String)> {
    SYNTHESISED
        .iter()
        .filter_map(|(slot, (group, field))| {
            let tier = match *group {
                "palette" => &r.palette,
                "bar" => &r.bar,
                "notif" => &r.notif,
                _ => &r.window,
            };
            get(tier, field).map(|v| (slot.to_string(), v.to_string()))
        })
        .collect()
}

/// Render the kitty colour file for one resolved note set.
pub fn emit_kitty(r: &Resolved) -> String {
    let synthesised;
    let tier: &[(String, String)] = match &r.base16 {
        Some(b16) => b16,
        None => {
            synthesised = synthesised_base16(r);
            &synthesised
        }
    };
    let mut out = String::from(HEADER);
    for (key, slot) in BASE16_MAP {
        if let Some(v) = get(tier, slot).filter(|v| schema::is_hex(v)) {
            out.push_str(&format!("{key} {}\n", with_hash(v)));
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::livery::resolve::resolve;
    use serde_json::{json, Value};

    fn resolved(fixture: &str) -> Resolved {
        let raw = std::fs::read_to_string(format!("tests/fixtures/{fixture}")).unwrap();
        let container: Value = serde_json::from_str(&raw).unwrap();
        resolve(&container).unwrap()
    }

    fn line<'a>(out: &'a str, key: &str) -> Option<&'a str> {
        out.lines()
            .find_map(|l| l.strip_prefix(key).and_then(|rest| rest.strip_prefix(' ')))
    }

    #[test]
    fn base16_maps_onto_the_tinted_kitty_slots() {
        let r = resolved("valid-base16.json");
        let b = |k: &str| get(r.base16.as_ref().unwrap(), k).unwrap().to_string();
        let out = emit_kitty(&r);
        for (key, slot) in [
            ("background", "base00"),
            ("foreground", "base05"),
            ("selection_background", "base03"),
            ("cursor", "base05"),
            ("color0", "base00"),
            ("color1", "base08"),
            ("color2", "base0B"),
            ("color3", "base0A"),
            ("color4", "base0D"),
            ("color5", "base0E"),
            ("color6", "base0C"),
            ("color7", "base05"),
            ("color8", "base02"),
            ("color9", "base08"),
            ("color15", "base07"),
            ("color16", "base09"),
            ("color17", "base0F"),
            ("color21", "base06"),
        ] {
            assert_eq!(line(&out, key), Some(b(slot).as_str()), "{key} ← {slot}");
        }
        // Every ANSI slot 0–21 is present exactly once.
        for n in 0..=21 {
            let key = format!("color{n}");
            assert_eq!(
                out.lines()
                    .filter(|l| l.split(' ').next() == Some(key.as_str()))
                    .count(),
                1,
                "{key}"
            );
        }
    }

    #[test]
    fn a_note_without_base16_writes_every_slot_from_the_facets_synthesised_scheme() {
        let r = resolved("valid.json");
        assert!(r.base16.is_none());
        let out = emit_kitty(&r);
        // The same slot set as a base16 note: nothing of an earlier song survives.
        let keys = |o: &str| -> Vec<String> {
            o.lines()
                .filter(|l| !l.starts_with('#'))
                .map(|l| l.split(' ').next().unwrap().to_string())
                .collect()
        };
        assert_eq!(
            keys(&out),
            keys(&emit_kitty(&resolved("valid-base16.json")))
        );
        assert_eq!(keys(&out).len(), BASE16_MAP.len());
        assert_eq!(line(&out, "background"), Some("#1e1e2e")); // base00 ← bg
        assert_eq!(line(&out, "foreground"), Some("#cdd6f4")); // base05 ← fg
        assert_eq!(line(&out, "cursor"), Some("#cdd6f4")); // base05, as the baked kitty.conf
        assert_eq!(line(&out, "color1"), Some("#f38ba8")); // base08 ← notif.urgent ← urgent
        assert_eq!(line(&out, "color2"), Some("#89b4fa")); // base0B ← accent
        assert_eq!(line(&out, "color4"), Some("#89b4fa")); // base0D ← window.border ← accent
        assert_eq!(line(&out, "color5"), Some("#a6e3a1")); // base0E ← bar.accent (authored)
        assert_eq!(line(&out, "color8"), Some("#1e1e2e")); // base02 ← window.borderInactive ← bg
        assert_eq!(line(&out, "color18"), Some("#1e1e2e")); // base01 ← bar.bg ← bg
    }

    #[test]
    fn the_synthesised_scheme_is_all_sixteen_slots_in_order() {
        let s = synthesised_base16(&resolved("valid.json"));
        let slots: Vec<&str> = s.iter().map(|(k, _)| k.as_str()).collect();
        let want: Vec<String> = (0..16).map(|n| format!("base0{n:X}")).collect();
        assert_eq!(slots, want);
    }

    #[test]
    fn a_non_hex_value_is_never_written_as_a_config_line() {
        let r = resolve(&json!({
            "schemaVersion": "0",
            "palette": {
                "bg": "#000000\nshell /bin/evil",
                "fg": "#ffffff",
                "accent": "#00ff00",
                "urgent": "#ff0000",
                "hot": "#ffff00"
            }
        }))
        .unwrap();
        let out = emit_kitty(&r);
        assert!(!out.contains("evil"), "{out}");
        assert_eq!(line(&out, "background"), None);
        assert_eq!(line(&out, "foreground"), Some("#ffffff"));
    }

    #[test]
    fn every_line_is_a_comment_or_a_key_and_one_hex_colour() {
        let out = emit_kitty(&resolved("valid-base16.json"));
        for l in out.lines() {
            if l.starts_with('#') {
                continue;
            }
            let (k, v) = l.split_once(' ').expect(l);
            assert!(
                !k.is_empty() && schema::is_hex(v) && v.starts_with('#'),
                "{l}"
            );
        }
    }
}
